replicaCount: 2

image:
  repository: fastapiacrdm.azurecr.io/dmfastapi-app
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

containerPort: 8000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
