name: Deploy FastAPI to AKS

on:
  push:
    branches:
      - main 

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCE_GROUP: "fastapi-rg"
  AZURE_AKS_CLUSTER: "fastapi-aks-cluster-dm"
  ACR_NAME: "fastapiacrdm"
  IMAGE_NAME: "dmfastapi-app"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up kubelogin
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: "v0.2.12"

      - name: Login to Azure Container Registry (ACR)
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest .

      - name: Push Docker Image to ACR
        run: |
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Set AKS Context
        uses: azure/aks-set-context@v5
        with:
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ env.AZURE_AKS_CLUSTER }}
          admin: "false"
          use-kubelogin: "true"

      - name: Update Deployment in AKS
        run: |
          kubectl set image deployment/dmfastapi-app fastapi=$ACR_NAME.azurecr.io/$IMAGE_NAME:latest
          kubectl rollout restart deployment/dmfastapi-app
          kubectl rollout status deployment/dmfastapi-app
